// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  textbookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'], // intro.md at root of /docs
      collapsed: false,
    },

    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'content/modules/001-ros2-fundamentals',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'content/modules/002-digital-twin',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac)',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'content/modules/003-ai-robot-brain',
        },
      ],
    },

    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'content/modules/004-vla',
        },
      ],
    },
  ],
};

module.exports = sidebars;
